// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.g.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz3j0YWdA9-ULeZ614MlENSwvHcMnPlVU',
    appId: '1:704109638785:android:8a3993a6e2b15fdd87c980',
    messagingSenderId: '704109638785',
    projectId: 'linum-dev',
    storageBucket: 'linum-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6DoOfzz6PEobCtn0_vlk5V5tt4Lobcc8',
    appId: '1:704109638785:ios:28a4e6ecf9b523c587c980',
    messagingSenderId: '704109638785',
    projectId: 'linum-dev',
    storageBucket: 'linum-dev.appspot.com',
    androidClientId: '704109638785-jv83ak0lhjok25gjptnbqbo7ubk9kla7.apps.googleusercontent.com',
    iosClientId: '704109638785-vdogvirir21e8l356geelo8s4bqagpl4.apps.googleusercontent.com',
    iosBundleId: 'de.investitacademy.linum',
  );
}
