# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :testmatch do
    match(git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHENTICATION'], readonly: true)
  end

  lane :localBeta do
    disable_automatic_code_signing(path: "Runner.xcodeproj")
    match(readonly: true)
    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )
  end

  lane :beta do
    disable_automatic_code_signing(path: "Runner.xcodeproj")

    create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV['MATCH_KEYCHAIN_PASSWORD'],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    match(
        type: "appstore",
        git_basic_authorization: ENV['GIT_BASIC_AUTH_TOKEN'],
        readonly: true,
        keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
        keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )

    api_key = app_store_connect_api_key(
        key_id: "C78AQSB7DP",
        issuer_id: "053633dd-686e-4ec2-90dd-98af3f2296aa",
        key_filepath: "./AuthKey.p8"
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )

    upload_to_testflight(
        api_key: api_key
    )
  end

  lane :release do
    disable_automatic_code_signing(path: "Runner.xcodeproj")

    create_keychain(
        name: ENV['MATCH_KEYCHAIN_NAME'],
        password: ENV['MATCH_KEYCHAIN_PASSWORD'],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    match(
        type: "appstore",
        git_basic_authorization: ENV['GIT_BASIC_AUTH_TOKEN'],
        readonly: true,
        keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
        keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD']
    )

    api_key = app_store_connect_api_key(
        key_id: "C78AQSB7DP",
        issuer_id: "053633dd-686e-4ec2-90dd-98af3f2296aa",
        key_filepath: "./AuthKey.p8"
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )

    upload_to_app_store(
        api_key: api_key
    )
  end
end

