# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do
    api_key = app_store_connect_api_key(
        key_id: "C78AQSB7DP",
        issuer_id: "053633dd-686e-4ec2-90dd-98af3f2296aa",
        key_filepath: "/Users/damattl/Development/Auth/AuthKey_C78AQSB7DP.p8"
    )
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )

    upload_to_testflight(
        api_key: api_key
    )
  end

  lane :release do
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    upload_to_app_store
  end
end

