# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play Store"
  lane :beta do
    upload_to_play_store(
        track: 'beta'
        aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    upload_to_play_store(
        aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
